branch-defaults:
  getting-things-up-on-eb:
    environment: network-vis
  master:
    environment: network-vis
    group_suffix: null
  setup-d3:
    environment: network-vis
global:
  application_name: network-vis
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
